### ISSUE TITLE
phonon spectra from ALIGNN force fields

### ISSUE THREAD

**Issue by antonf-ekb** [usnistgov/alignn#134]
Hello!
It is probably not a bug report but a question regarding using ALIGNN force fields for calculating phonon spectra of solids. In the entropy_from_FF jupyter notebook there is example showing nice phonon bandstructure calculated based on ALIGNN force fields for Cu, but when I try to use it for other systems e.g. "feg" from the same notebook or some compounds known to be stable, I obtain  bandstructures with many nagative branches. This is independent on the supercell size and geometry optimization. So my question - is it inevitably or can I somehow get rid of these negative branches?

Best regards,
Anton.

**Comment by knc6** [comment]
Hi @antonf-ekb 

Phonon/thermal property predictions using ALIGNN-FF are still very much work in progress as you mentioned in the [notebook](https://github.com/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/Entropy.ipynb).

Hopefully, with better models  (coming soon), we would be able to get rid of unphysical negative phonons.
