### ISSUE TITLE
AttributeError: module 'dgl' has no attribute 'DGLGraph'

### ISSUE THREAD

**Issue by Jia-12138** [usnistgov/alignn#137]
**Describe the bug**
AttributeError: module 'dgl' has no attribute 'DGLGraph'when input  train_folder.py --root_dir "alignn/examples/sample_data" --config "alignn/examples/sample_data/config_example.json" --output_dir=temp (windows system)
**my env**
torch                      2.0.0
torchaudio                 2.1.1+cu118
torchvision                0.16.1+cu118
dgl                        1.0.2+cu118
python                   3.10.13
![image](https://github.com/usnistgov/alignn/assets/136157142/006bc79b-55a7-4a74-87db-4854dc42def7)

**Comment by knc6** [comment]
If you haven't already, please use a lower version of dgl for now, say `pip install dgl==0.6.0`.
We will try to get ALIGNN to latest version of dgl soon.
