### ISSUE TITLE
from jarvis.db.figshare import data

### ISSUE THREAD

**Issue by xiaowangfeng** [usnistgov/alignn#168]
Hello Professor. I am encountering an error when utilising the jarvis dataset. I have installed jarvis-tools-2024.8.30 and jarvis-0.1.9 but I am running:
from jarvis.db.figshare import data
d = data(‘dft_3d’) #choose a name of dataset from above
print (d[0].keys())
print(len(d))
I'm getting an error.
d = data(‘dft_3d’) #choose a name of dataset from above
File ‘D:\Anaconda\envs\DL\lib\site-packages\jarvis\db\figshare.py’, line 588, in data
dat = get_request_data(js_tag=js_tag, url=url, store_dir=store_dir)
File ‘D:\Anaconda\envs\DL\lib\site-packages\jarvis\db\figshare.py’, line 541, in get_request_data
data = json.loads(zipfile.ZipFile(path).read(js_tag))
File ‘D:\Anaconda\envs\DL\lib\zipfile.py’, line 1266, in init
self._RealGetContents()
File ‘D:\Anaconda\envs\DL\lib\zipfile.py’, line 1333, in _RealGetContents
raise BadZipFile(‘File is not a zip file’)
zipfile.BadZipFile: File is not a zip file
Can you tell me how to fix him?

**Comment by bdecost** [comment]
I think you may have a broken download - `jarvis.db` first downloads a zip archive from figshare, then loads the data from there.

The data archives are stored in the source tree - try checking or removing the zip archives from `D:/Anaconda/envs/DL/lib/site-packages/jarvis/db` (there should be a file named `jdft_3d-12-12-2022.json.zip` or similar in that directory) and then rerunning `jarvis.db.figshare.data("dft_3d")`, which will re-download the zip archive

**Comment by xiaowangfeng** [comment]
Thanks for your reply, I tried your method and there is indeed the jdft_3d-12-12-2022.json.zip file inside the directory. But when I deleted and rerun the programme, the same problem occurs on the basis.

**Comment by bdecost** [comment]
ok. can you please verify that the md5 checksum matches what [the figshare page](https://figshare.com/articles/dataset/jdft_3d-7-7-2018_json/6815699?file=38521619) has: it should be `fb3e1eb80339a70ff313af1c644c1777`, which you can check by running the program `md5sum` on the zip file

you could also try to unzip the file in your OS's file manager, the contents should be a single 200 MB json file

If the zip archive is corrupted, you could directly download the zip archive from figshare and place it at the path that Jarvis-tools expects

if the zip archive is not the issue, I'll have to think about the next debugging step.

**Comment by xiaowangfeng** [comment]
Thanks for the suggestion, I ran：
from jarvis.db.figshare import data
d = data(‘dft_3d’) #choose a name of dataset from above
# See available keys
print (d[0].keys())
# See available keys print (d[0].keys())
print(len(d))
it can succeed.
But when I run：
 from jarvis.db.figshare import data
d = data(‘dft_3d_2021’) #choose a name of dataset from above
# See available keys
print (d[0].keys())
# See available keys print (d[0].keys())
print(len(d))
it will reappear with the error dft_3d = data(dataset=‘dft_3d_2021’)
  File ‘D:\Anaconda\envs\DL\lib\site-packages\jarvis\db\figshare.py’, line 552, in data
    dat = get_request_data(js_tag=js_tag, url=url, store_dir=store_dir)
  File ‘D:\Anaconda\envs\DL\lib\site-packages\jarvis\db\figshare.py’, line 505, in get_request_data
    data = json.loads(zipfile.ZipFile(path).read(js_tag))
  File ‘D:\Anaconda\envs\DL\lib\zipfile.py’, line 1472, in read
    with self.open(name, ‘r’, pwd) as fp.
  File ‘D:\Anaconda\envs\DL\lib\zipfile.py’, line 1511, in open
    zinfo = self.getinfo(name)
  File ‘D:\Anaconda\envs\DL\lib\zipfile.py’, line 1438, in getinfo
    raise KeyError(
KeyError: ‘There is no item named “jdft_3d-8-18-2021.json” in the archive’
What is the reason for this?

**Comment by bdecost** [comment]
I'm not sure. You were first having issues with the `dft_3d` dataset - how did you resolve that issue?

Have you checked the integrity of the jdft_3d-8-18-2021.json.zip archive for the `dft_3d_2021` dataset? it seems like the problem may be related to the download process itself...

**Comment by xiaowangfeng** [comment]
I'm sorry, i have solved this problem. thanks
