### ISSUE TITLE
where I can get the total energy data in the jarvis dataset.

### ISSUE THREAD

**Issue by xiaowangfeng** [usnistgov/alignn#170]
Hello professor, I found that ALIGNN can train total energy, but I checked the jarvis dataset and found that the material did not include total energy.
I would like to know where I can get the total energy data in the jarvis dataset.

**Comment by xiaowangfeng** [comment]
Looking forward to your reply.

**Comment by bdecost** [comment]
the `dft_3d` dataset has a column for `optb88vdw_total_energy`, is that what you are looking for?

Alternatively, the force field dataset also has total energies (IIRC they are on a per-atom basis)

**Comment by xiaowangfeng** [comment]
Thanks for your reply, can you provide a visualization site to find the total energy of each crystal?

**Comment by bdecost** [comment]
Sorry, I'm not sure what you mean by visualization site. Do you mean something like the jarvis-dft record pages, like https://www.ctcms.nist.gov/~knc6/static/JARVIS-DFT/JVASP-42549.xml ?

this page has a visualization of the crystal structure, and reports `Relaxed energy/atom (eV): -7.00006`, which I think corresponds to the `optb88vdw_total_energy` field in the [dft_3d dataset](https://doi.org/10.6084/m9.figshare.6815699)

**Comment by xiaowangfeng** [comment]
Yes，the record pages are what i want . But are you sure that the Relaxed energy/atom corresponds to the total_energy? As far as i know, they are different.

**Comment by bdecost** [comment]
I think it depends on which dataset you are interested in. `dft_3d` consists of relaxed crystal structures, so the relaxed energy reported on this web page is the total energy of the structure after the final geometry optimization step, which I think is what you want

You can verify by downloading the vasp outputs linked at the bottom of the page [DFT-SCF](https://ndownloader.figshare.com/files/23366768) -- the total energy reported in the last step of the OUTCAR file is -168.00145926 eV, which matches the energy reported on the web page: -168.00145926 eV / 24 atoms -> -7.000060802499999 eV/atom

**Comment by bdecost** [comment]
I just checked, the `optb88vdw_total_energy` field of the `dft_3d` dataset has the value -7.00006 for this material, so `optb88vdw_total_energy` is the field that you want, and it is stored in the dataset on a per atom basis

**Comment by xiaowangfeng** [comment]
thank you, I think your are right.

**Comment by knc6** [comment]
In addition to Brian's comment, you can check out the following colab notebook to analyze data distribution 
https://colab.research.google.com/github/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/Analyzing_data_in_the_JARVIS_DFT_dataset.ipynb
