### ISSUE TITLE
Per-material input features

### ISSUE THREAD

**Issue by tawe141** [usnistgov/alignn#171]
Is there a way to add a global input feature, ie one that is per-material but not per-atom?

**Comment by knc6** [comment]
I am still testing it, but check out this additional output example 

https://github.com/usnistgov/alignn/blob/develop/alignn/examples/sample_data_ff_additional/config.json#L80

**Comment by tawe141** [comment]
Thanks Kamal, but this appears to be for additional outputs, whereas I would like to add additional features as input.

**Comment by tawe141** [comment]
Oops never mind, found the right example.  

https://github.com/usnistgov/alignn/tree/main/alignn/examples/sample_data_ff_feats

Thanks!
