### ISSUE TITLE
Running the regression example

### ISSUE THREAD

**Issue by sadmanomee** [usnistgov/alignn#47]
1. There is no train_folder.py inside alignn/scripts folder
2. Even if you copy it there, the problem still resides with "import alignn.data" because it is not inside that folder
3. It works if you copy train_folder.py in the root directory, but still has more errors/issues.

**Comment by bdecost** [comment]
it looks like @knc6 moved this script to [alignn/train_folder.py](https://github.com/usnistgov/alignn/blob/main/alignn/train_folder.py) recently, possibly in connection with #35? In any case we should update the README accordingly

Have you installed the alignn package through pip? It seems like maybe you are having issues with alignn modules not being found in `PYTHONPATH`, but it's hard to tell without more detail -- if you can share the stack trace you get from (2) and (3) it will be easier to help you sort things out

If you haven't installed the alignn package through pip, you need to either run `ipython alignn/train_folder.py  ARGS` or explicitly add the repository root/working directory to your `PYTHONPATH`, as in `PYTHONPATH=.:${PYTHONPATH} python alignn/train_folder.py ARGS`

For example, I tend to run code from the repository root, like `ipython alignn/cli.py /path/to/modeldir/config.json` -- [alignn/cli.py](https://github.com/usnistgov/alignn/blob/main/alignn/cli.py) is a thin commandline wrapper around [alignn/train.py](https://github.com/usnistgov/alignn/blob/main/alignn/train.py) that only supports datasets available through `jarvis.db.figshare` right now.

**Comment by knc6** [comment]
In addition to @bdecost response, I have modified the README file. 

These [pytests](https://github.com/usnistgov/alignn/blob/main/alignn/tests/test_prop.py#L38) seem to pass as well as the [ colab notebook](https://colab.research.google.com/github/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/Training_ALIGNN_model_example.ipynb) is working fine.

If you are still  getting any error, you can paste the error message here.

**Comment by sadmanomee** [comment]
I think you did what I suggested in (2), but I still get this error - 
"Traceback (most recent call last):
  File "alignn/train_folder.py", line 8, in <module>
    from alignn.data import get_train_val_loaders
ModuleNotFoundError: No module named 'alignn'"

I think this is because the train_folder.py file is already inside the alignn folder, so trying to do "from alignn.data import get_train_val_loaders" tries to find another folder named alignn inside the alignn folder (which is not there). Can you check this one?

**Comment by bdecost** [comment]
```python
from alignn.data import get_train_val_loaders
ModuleNotFoundError: No module named 'alignn'"
```

this is an absolute import for the function [get_train_val_loaders](https://github.com/usnistgov/alignn/blob/main/alignn/data.py#L223) -- `ModuleNotFoundError` indicates that the whole alignn module is not on your python load path. Can you `import alignn` without error from a REPL running in the repository root? 

```python
In [5]: import alignn

In [6]: from alignn.data import get_train_val_loaders

In [7]: from alignn.nonexistent import test
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-4f47ed4e5dea> in <module>
----> 1 from alignn.nonexistent import test

ModuleNotFoundError: No module named 'alignn.nonexistent'
```

Have you double checked your python environment, load path (and working directory if you have not installed alignn with pip)?

**Comment by sadmanomee** [comment]
Thank you very much, it runs now.
