### ISSUE TITLE
OMDB Dataset Import Error

### ISSUE THREAD

**Issue by MiracAydin1** [usnistgov/alignn#49]
Dear All,

First of all, thanks for creating ALIGNN tool.

I am trying to train a model with OMDB dataset to obtain a bandgap prediction. The dataset containes xyz files of molecules and bandgap values of them. It is also included in JARVIS documentation:
[https://jarvis-tools.readthedocs.io/en/master/databases.html](url)

I am following the README file on ALIGNN page. I generated my xyz samples from the dataset as it follows without any problem:

`
from jarvis.db.figshare import data as jdata
from jarvis.core.atoms import Atoms

omdbset = jdata("omdb")
prop = "bandgap"

max_samples = 12500
f = open("id_prop.csv", "w")
count = 0
for i in omdbset:
    atoms = Atoms.from_dict(i["atoms"])
    cod_id = i["cod_id"]
    xyz_name = "OMDB-" + cod_id + ".xyz"
    target = i[prop]
    if target != "na":
        atoms.write_xyz(xyz_name)
        f.write("%s,%6f\n" % (xyz_name, target))
        count += 1
        if count == max_samples:
            break
f.close()
`

I used the config.json file like you did it in QM9 training. Just the following 2 lines are different:

` "dataset": "omdb",
  "target": "bandgap",`

When i tried to run the code like this, it gave the following errors:

`python /home/fsysadmin/alignn/alignn/train_folder.py --root_dir "/home/fsysadmin/alignn/omdb_tests/prep_data" --config "/home/fsysadmin/alignn/omdb_tests/prep_data/config.json" --file_format xyz --output_dir=/home/fsysadmin/alignn/omdb_tests/results`

`Using backend: pytorch
Check 1 validation error for TrainingConfig
dataset
  unexpected value; permitted: 'dft_3d', 'jdft_3d-8-18-2021', 'dft_2d', 'megnet', 'megnet2', 'mp_3d_2020', 'qm9', 'qm9_dgl', 'qm9_std_jctc', 'user_data', 'oqmd_3d_no_cfid', 'edos_up', 'edos_pdos', 'qmof', 'hmof', 'hpov', 'pdbbind', 'pdbbind_core' (type=value_error.const; given=omdb; permitted=('dft_3d', 'jdft_3d-8-18-2021', 'dft_2d', 'megnet', 'megnet2', 'mp_3d_2020', 'qm9', 'qm9_dgl', 'qm9_std_jctc', 'user_data', 'oqmd_3d_no_cfid', 'edos_up', 'edos_pdos', 'qmof', 'hmof', 'hpov', 'pdbbind', 'pdbbind_core'))
Traceback (most recent call last):
  File "/home/fsysadmin/alignn/alignn/train_folder.py", line 194, in <module>
    train_for_folder(
  File "/home/fsysadmin/alignn/alignn/train_folder.py", line 80, in train_for_folder
    config.keep_data_order = keep_data_order
AttributeError: 'dict' object has no attribute 'keep_data_order'`

As i understand from the error output, OMDB dataset is not included into ALIGNN package. Giving the full path of OMDB tar file did not also solve the problem.

How can i include OMDB dataset? There are some scripts that import dataset in alignn repo such as train_all_qm9_jctc.py. Maybe this scripts can be modified to include OMDB.

I appreciate your help.

Best regards,

**Comment by MiracAydin1** [comment]
I removed "dataset": "omdb" and "target": "bandgap" lines from the config.json file. The result is below:

`Using backend: pytorch
Traceback (most recent call last):
  File "/home/fsysadmin/alignn/alignn/train_folder.py", line 194, in <module>
    train_for_folder(
  File "/home/fsysadmin/alignn/alignn/train_folder.py", line 150, in train_for_folder
    ) = get_train_val_loaders(
  File "/raid/apps/alignn/2021/lib/python3.8/site-packages/alignn/data.py", line 333, in get_train_val_loaders
    if isinstance(i[target], list):  # multioutput target
KeyError: 'formation_energy_peratom'`

**Comment by knc6** [comment]
Hi @MiracAydin1 you don't need to change or remove dataset and target values from the config file. When you use train_folder.py, your dataset and target must be "user_data" and "target" respectively, same as the example file. Try running the script without the changing them, and let me know if you still see the issue.

Also, in case of OMDB, you should should use POSCAR or cif format, not XYZ. Structures in OMDB are semi-crystalline and not molecular i.e. they have periodic boundary conditions.

**Comment by MiracAydin1** [comment]
Hi @knc6,

Thank you so much for the explanation. Model is working right now. 
After this step, I will tune the parameters in config file to obtain best results with OMDB.

Thanks for the help.
