### ISSUE TITLE
Python API for web form?

### ISSUE THREAD

**Issue by janosh** [usnistgov/alignn#63]
Is the JARVIS-ALIGNN web interface accessible via Python API? I'd like to get predictions for a few dozen POSCAR files without pasting them all in manually.

**Comment by knc6** [comment]
You can use the `pretrained.py` executable which comes with alignn installation for prediction, e.g.:

`pretrained.py --model_name jv_formation_energy_peratom_alignn --file_format poscar --file_path alignn/examples/sample_data/POSCAR-JVASP-10.vasp
`

**Comment by janosh** [comment]
Thanks, works great!
