### ISSUE TITLE
FF training does not work with best_model.pt

### ISSUE THREAD

**Issue by rashigeek** [usnistgov/alignn#98]
I am trying to retrain the force fields model on a dataset a created. I have successfully created an "id_prop.json" file and a config.json file as instructed in the README file. 

**Training from scratch seems to be fine**. The following command works as expected and the model starts training:

`train_folder_ff.py --root_dir "aliggn-ff-train-data" --config "aliggn-ff-train-data/config.json" --output_dir=temp`

**However, if I try to use the best_model.pt to restart training using the restart_model_path argument, the model does not train.** 

Here is an example of how to reproduce the issue:

`!train_folder_ff.py --root_dir "aliggn-ff-train-data" --config "aliggn-ff-train-data/config.json" --restart_model_path "/usr/local/lib/python3.10/dist-packages/alignn/ff/best_model.pt" --output_dir=temp`

Which gives the following error:
`

fatal: not a git repository (or any of the parent directories): .git
len dataset 12254
Restarting the model training: /usr/local/lib/python3.10/dist-packages/alignn/ff/best_model.pt
Rest config name='alignn_atomwise' alignn_layers=4 gcn_layers=4 atom_input_features=92 edge_input_features=80 triplet_input_features=40 embedding_features=64 hidden_features=256 output_features=1 grad_multiplier=-1 calculate_gradient=True atomwise_output_features=3 graphwise_weight=0.85 gradwise_weight=0.05 stresswise_weight=0.05 atomwise_weight=0.05 link='identity' zero_inflated=False classification=False force_mult_natoms=False include_pos_deriv=False
model ALIGNNAtomWise(
  (atom_embedding): MLPLayer(
    (layer): Sequential(
      (0): Linear(in_features=92, out_features=256, bias=True)
      (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (2): SiLU()
    )
  )
  (edge_embedding): Sequential(
    (0): RBFExpansion()
    (1): MLPLayer(
      (layer): Sequential(
        (0): Linear(in_features=80, out_features=64, bias=True)
        (1): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
        (2): SiLU()
      )
    )
    (2): MLPLayer(
      (layer): Sequential(
        (0): Linear(in_features=64, out_features=256, bias=True)
        (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (2): SiLU()
      )
    )
  )
  (angle_embedding): Sequential(
    (0): RBFExpansion()
    (1): MLPLayer(
      (layer): Sequential(
        (0): Linear(in_features=40, out_features=64, bias=True)
        (1): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
        (2): SiLU()
      )
    )
    (2): MLPLayer(
      (layer): Sequential(
        (0): Linear(in_features=64, out_features=256, bias=True)
        (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (2): SiLU()
      )
    )
  )
  (alignn_layers): ModuleList(
    (0-3): 4 x ALIGNNConv(
      (node_update): EdgeGatedGraphConv(
        (src_gate): Linear(in_features=256, out_features=256, bias=True)
        (dst_gate): Linear(in_features=256, out_features=256, bias=True)
        (edge_gate): Linear(in_features=256, out_features=256, bias=True)
        (bn_edges): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (src_update): Linear(in_features=256, out_features=256, bias=True)
        (dst_update): Linear(in_features=256, out_features=256, bias=True)
        (bn_nodes): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (edge_update): EdgeGatedGraphConv(
        (src_gate): Linear(in_features=256, out_features=256, bias=True)
        (dst_gate): Linear(in_features=256, out_features=256, bias=True)
        (edge_gate): Linear(in_features=256, out_features=256, bias=True)
        (bn_edges): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (src_update): Linear(in_features=256, out_features=256, bias=True)
        (dst_update): Linear(in_features=256, out_features=256, bias=True)
        (bn_nodes): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (gcn_layers): ModuleList(
    (0-3): 4 x EdgeGatedGraphConv(
      (src_gate): Linear(in_features=256, out_features=256, bias=True)
      (dst_gate): Linear(in_features=256, out_features=256, bias=True)
      (edge_gate): Linear(in_features=256, out_features=256, bias=True)
      (bn_edges): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (src_update): Linear(in_features=256, out_features=256, bias=True)
      (dst_update): Linear(in_features=256, out_features=256, bias=True)
      (bn_nodes): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
  )
  (readout): AvgPooling()
  (fc_atomwise): Linear(in_features=256, out_features=3, bias=True)
  (fc): Linear(in_features=256, out_features=1, bias=True)
)
Traceback (most recent call last):
  File "/usr/local/bin/train_folder_ff.py", line 309, in <module>
    train_for_folder(
  File "/usr/local/bin/train_folder_ff.py", line 239, in train_for_folder
    model.load_state_dict(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ALIGNNAtomWise:
	Missing key(s) in state_dict: "fc_atomwise.weight", "fc_atomwise.bias". 
`
**It seems that the saved model does not include weights or biases for fc_atomwise.** 

**A quick dirty fix to the issue is to set these weights and biases to zero and have the model learn these parameters from the dataset instead of training all parameters from scratch.** 

Here is a simple Python code to establish that:

import torch
from alignn.ff.ff import AlignnAtomwiseCalculator, default_path
from ase.io import read, write

model_path = default_path()
model_checkpoint = torch.load(model_path+'/best_model.pt', map_location=torch.device('cpu'))
duplicated_weight = model_checkpoint['fc.weight'].repeat(3, 1)*0
duplicated_bias = model_checkpoint['fc.bias'].repeat(3)*0
model_checkpoint['fc_atomwise.weight'] = duplicated_weight
model_checkpoint['fc_atomwise.bias'] = duplicated_bias
torch.save(model_checkpoint, 'updated_best_model.pt')
model_checkpoint['fc_atomwise.weight'] = model_checkpoint['fc.weight']
model_checkpoint['fc_atomwise.bias'] = model_checkpoint['fc.weight']

After running the code above. The model can be trained by using the following command:
`!train_folder_ff.py --root_dir "aliggn-ff-train-data" --config "aliggn-ff-train-data/config.json" --restart_model_path "updated_best_model.pt" --output_dir=temp`

I may be missing something here as well since I am not very well-versed in using pytorch. Please let me know.

**Comment by knc6** [comment]
@rashigeek thanks for reporting this issue.
I think this is due to variable type of `atomwise_output_features` parameters.
In our early versions of the code, we had kept it `None`, but it should be an integer, say 0.
I just made a PR https://github.com/usnistgov/alignn/pull/99/files and will merge in the main branch soon.
Hope this will fix your issue.

**Comment by rashigeek** [comment]
This issue has been fixed and training alignn-ff works.
